# https://github.com/actions/javascript-action

name: 'Decrypt Secrets'
description: 'Decrypt secrets from a JSON file using gpg'
author: 'Zennon Gosalvez'
inputs:
  secrets_file:
    description: 'The `gpg` file. For example, `.github/workflows/secrets.json.gpg`'
    required: true
  map:
    description: 'Describes the map between the environment variables and secret keys. For example, `SECRET_PASSWORD=PASSWORD,PASSPHRASE=passphrase`'
    required: true
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
branding:
  icon: unlock
  color: gray-dark